baseURL = "https://mmazzarolo.com"
title = "mmazzarolo.com"
languageCode = "en-us"

googleAnalytics = "UA-89798360-1"

enableRobotsTXT = true # generate robots.txt

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

# Menu
# [menu]
#   [[menu.main]]
#     url = "/blog"
#     name = "Blog"
#     weight = 1
#   [[menu.main]]
#     url = "/works/"
#     name = "Works"
#     weight = 2
#   [[menu.main]]
#     url = "/about/"
#     name = "About"
#     weight = 3

# Links format
[permalinks]
  blog = ":year/:month/:day/:title/"
  # page = "/:slug/"
