baseURL = "https://mmazzarolo.com"
title = "mmazzarolo.com"
languageCode = "en-us"

enableRobotsTXT = true # generate robots.txt

[params]
  description = "Matteo's personal website"

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
  [[menu.main]]
    url = "/blog"
    name = "Blog"
    weight = 1
  [[menu.main]]
    url = "/reviews/"
    name = "Reviews"
    weight = 2
  [[menu.main]]
    url = "/about/"
    name = "About"
    weight = 3

# Links format
[permalinks]
  blog = ":year/:month/:day/:title/"
